# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSmart < Formula
  desc "CLI tool to sync Git feature branches with the default branch."
  homepage "https://github.com/AEGON247/git-smart"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/AEGON247/git-smart/releases/download/v0.1.0/git-smart_0.1.0_darwin_amd64.tar.gz"
      sha256 "ca53ef8779bd9c577c01ba70c0b75da02b09e5f06f3cd80c5c8f7a47184b8866"

      def install
        bin.install "git-smart"
      end
    end
    on_arm do
      url "https://github.com/AEGON247/git-smart/releases/download/v0.1.0/git-smart_0.1.0_darwin_arm64.tar.gz"
      sha256 "d5105665ba7b27734c711fdd85d5a9b06acaf8d03b22acd685fd030f3288980f"

      def install
        bin.install "git-smart"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AEGON247/git-smart/releases/download/v0.1.0/git-smart_0.1.0_linux_amd64.tar.gz"
        sha256 "688c0c76d8f94036d6fe0e4811344c8ef6ee74c11f31a03f185891ebbcea23fb"

        def install
          bin.install "git-smart"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AEGON247/git-smart/releases/download/v0.1.0/git-smart_0.1.0_linux_arm64.tar.gz"
        sha256 "9fae2f21c42db6525ac041e0e75d92bfcf95f1b39971d39a2a833b4407e9e7d9"

        def install
          bin.install "git-smart"
        end
      end
    end
  end
end
