# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSmart < Formula
  desc "CLI tool to sync Git feature branches with the default branch."
  homepage "https://github.com/AEGON247/git-smart"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/AEGON247/git-smart/releases/download/v0.1.1/git-smart_0.1.1_darwin_amd64.tar.gz"
      sha256 "02829c408c80acef81a79dba45055db11d7365a6d0f3e0213ae2d1d9eef7ff65"

      def install
        bin.install "git-smart"
      end
    end
    on_arm do
      url "https://github.com/AEGON247/git-smart/releases/download/v0.1.1/git-smart_0.1.1_darwin_arm64.tar.gz"
      sha256 "1a37a944abe82beb34213cd3feb984196708c8ab5f77eca85e7fe63cb8780b11"

      def install
        bin.install "git-smart"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AEGON247/git-smart/releases/download/v0.1.1/git-smart_0.1.1_linux_amd64.tar.gz"
        sha256 "419239279c281d1c0ad1e562014769895c8af49a232a464445ffedc0101db5ac"

        def install
          bin.install "git-smart"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AEGON247/git-smart/releases/download/v0.1.1/git-smart_0.1.1_linux_arm64.tar.gz"
        sha256 "36a2703879b716bf599230d7984f3ac42ea9dbd9a9673bf37cbcf48adfb190f7"

        def install
          bin.install "git-smart"
        end
      end
    end
  end
end
